sudo: false
dist: trusty
notifications:
  email: false
addons:
  apt:
    packages:
      - bison
      - automake
      - build-essential
      - git
      - python-sphinx
      - libssl-dev
      - libtool
      - libxml2-dev
      - libyaml-dev
      - llvm-dev
      - make
      - wget
      - xz-utils
      - zlib1g-dev
      - clang
language: c
compiler:
  - clang
  - gcc

cache:
  apt: true
  directories:
  - $HOME/wslay
  - $HOME/opt

env:
  - MRUBY_VERSION=1.3.0
  - MRUBY_VERSION=master

install:
  - ./travis-install-wslay.sh
  - ./travis-install-libressl.sh
  - export LD_LIBRARY_PATH=$HOME/opt/libressl/lib:$LD_LIBRARY_PATH

script:
  - MRUBY_CONFIG=build_config_travis.rb rake clean
  - MRUBY_CONFIG=build_config_travis.rb rake test
